---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-{{ name }}
  namespace: {{ .namespace }}

{{- if not .namespace }}
{{- fail "Namespace is required" }}
{{- end }}
{{- if not .name }}
{{- fail "Name is required" }}
{{- end }}
{{- if not .version }}
{{- fail "Version is required" }}
{{- end }}
